### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by mda1125** [md-howsa/GoLDAP#1]
I am trying to use this to test against an LDAP server located at:

https://www.zflexldapadministrator.com/index.php/blog/82-free-online-ldap

First lines to connect to the server are:

ldap_server = 'ldap://104.223.95.149:389'
us = 'ro_admin' 
pw = 'zflexpass' 

base_dn =  'dc=zflexsoftware,dc=com'

When I run the script 

python3 goLDAP.py this is what I get

  File "goLDAP.py", line 66
    print len(result)
          ^
SyntaxError: invalid syntax

**Comment by md-howsa** [comment]
Use Python 2.7 instead of python 3 
I will upgrade the code soon to be compatible with Python3 
but for the time being you can only use Python 2.7

**Comment by mda1125** [comment]
Ah okay.  Got past that syntax error

Now I'm stuck at "no module named ldap"

**Comment by md-howsa** [comment]
Because you have to install the requirements of the scripts first by running this in the folder of the script:

pip install -r requirements.txt
